baseURL = '/'
languageCode = 'en-us'
title = 'ABeltramo'
theme = "terminal"

[params]

contentTypeName = "blog"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 4

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = true

# if your resource directory contains an image called `cover.(jpg|png|webp)`,
# then the file will be used as a cover automatically.
# With this option you don't have to put the `cover` param in a front-matter.
autoCover = false

# set post to show the last updated
# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
showLastUpdated = false

[params.author]
email = 'beltramo.ale@gmail.com'
name = 'ABeltramo'

[languages]
[languages.en]
languageName = "English"
title = "ABeltramo"

[languages.en.params]
subtitle = "Personal blog and notes from ABeltramo"
owner = ""
keywords = ""
copyright = "© ABeltramo"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"
minuteReadingTime = "min read"
words = "words"

[languages.en.params.logo]
logoText = "ABeltramo"
logoHomeLink = "/"

[menus]
[[menus.main]]
name = "Blog"
url = "/blog"
weight = 10

[[menus.main]]
name = "Notes"
url = "/notes"
weight = 20

[[menus.main]]
name = "Github"
url = "https://github.com/ABeltramo"
weight = 30

[[menus.main]]
name = "RSS"
url = "/index.xml"
weight = 40

# Allow asciidoctor
[security]
[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', "^asciidoctor$"]

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']
taxonomy = ['html']
term = ['html']